/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Paarkavi Saravanan
 */
public class certifi extends javax.swing.JFrame {

    /**
     * Creates new form certifi
     */
    public certifi() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       date(); 
    }
    
    public certifi(String s)
    {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jLabel3.setText(s);
        date();
        
    }
    public void date(){
        String t=new SimpleDateFormat("dd/MM/yyy",Locale.FRANCE).format(new Date());
        jLabel8.setText(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        wayout = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 340, 65, 25);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Certificate of Honor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 50, 460, 42);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("We proudly present to");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 120, 197, 31);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("NAME SURNAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 160, 165, 37);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("with the award in recognition for your");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 210, 402, 45);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(185, 219, 164, 0);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("dedicated performance in quiz contest!!");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 250, 415, 35);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATE:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 320, 40, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/WhatsApp Image 2020-11-02 at 10.30.44 AM.jpeg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 640, 400);

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 170, 40, 14);

        wayout.setFont(new java.awt.Font("Tempus Sans ITC", 2, 36)); // NOI18N
        wayout.setText("WAY OUT");
        wayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wayoutActionPerformed(evt);
            }
        });
        getContentPane().add(wayout);
        wayout.setBounds(660, 460, 210, 50);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 520, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wayoutActionPerformed
        // TODO add your handling code here:
     
        
            new thank1().setVisible(true);
            this.setVisible(false);
             FileWriter f=null;
            BufferedWriter b=null;
            try {
                f=new FileWriter("C:\\Users\\Dell\\Documents\\NetBeansProjects\\project\\quiz.txt",true);
                b=new BufferedWriter(f);
                b.append("    Status : PASS");
                b.newLine();
                //b.append("last name:"+l);
                b.close();
                
            } catch (IOException ex) {
                Logger.getLogger(enroll.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_wayoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(certifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(certifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(certifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(certifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new certifi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton wayout;
    // End of variables declaration//GEN-END:variables
}
