/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Paarkavi Saravanan
 */
public class enroll extends javax.swing.JFrame {

    /**
     * Creates new form enroll
     */
    public enroll() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        testmyquiz.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        testmyquiz = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("ENROLLMENT FORM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(730, 40, 570, 120);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 150, 130, 40);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel4.setText("College / School Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 200, 230, 30);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel5.setText("Email id:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 240, 150, 40);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel6.setText("Phone number:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(690, 290, 200, 40);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel7.setText("Designation:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(690, 340, 180, 40);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel8.setText("Location:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(690, 390, 130, 40);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel9.setText("City");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(690, 440, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel10.setText("State:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(690, 470, 130, 50);
        getContentPane().add(firstname);
        firstname.setBounds(980, 160, 310, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(980, 210, 310, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(980, 250, 310, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(980, 300, 310, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(980, 400, 310, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(980, 440, 310, 30);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(980, 490, 310, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jRadioButton1.setText("Student");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(980, 350, 120, 33);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jRadioButton2.setText("Faculty");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(1170, 350, 110, 33);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUIZOPHILE...");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 130, 410, 80);

        submit.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(670, 590, 200, 50);

        testmyquiz.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        testmyquiz.setText("SPECIFICATION");
        testmyquiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testmyquizActionPerformed(evt);
            }
        });
        getContentPane().add(testmyquiz);
        testmyquiz.setBounds(960, 590, 230, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/register.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 120, 680, 390);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/full color.jpeg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 680, 130);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/full color.jpeg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(680, -6, 700, 510);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/full color.jpeg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(677, 504, 850, 200);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/full color.jpeg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-10, 500, 690, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testmyquizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testmyquizActionPerformed
        // TODO add your handling code here:
          String s=firstname.getText();
          //new certifi(s).setVisible(true);
        new rules(s).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_testmyquizActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "YOUR INFORMATION IS SUBMITTED SUCCESSFULLY!!\nALL THE BEST!!");
        testmyquiz.setEnabled(true);
        submit.setEnabled(false);
        String s=firstname.getText();
     
       // String l=lastname.getText();
       if(evt.getSource()==submit)
        {
            FileWriter f=null;
            BufferedWriter b=null;
            try {
                f=new FileWriter("C:\\Users\\Dell\\Documents\\NetBeansProjects\\project\\quiz.txt",true);
                b=new BufferedWriter(f);
                b.append("Name : "+s);
                //b.newLine();
                //b.append("last name:"+l);
                b.close();
                
            } catch (IOException ex) {
                Logger.getLogger(enroll.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
       
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton submit;
    private javax.swing.JButton testmyquiz;
    // End of variables declaration//GEN-END:variables
}
