/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Paarkavi Saravanan
 */
public class level1 extends javax.swing.JFrame {
public int mark=0;
String var;
    /**
     * Creates new form level1
     */
    public level1() {
        initComponents();
         
         setExtendedState(JFrame.MAXIMIZED_BOTH);
         explanation1.setEnabled(false);
         explanation2.setEnabled(false);
         explanation3.setEnabled(false);
         explanation4.setEnabled(false);
         explanation5.setEnabled(false);
         explanation6.setEnabled(false);
         explanation7.setEnabled(false);
         explanation8.setEnabled(false);
         explanation9.setEnabled(false);
         explanation10.setEnabled(false);
         watch w=new watch();
         w.start();
    }
 public level1(String a) {
        initComponents();
         var=a;
         setExtendedState(JFrame.MAXIMIZED_BOTH);
         explanation1.setEnabled(false);
         explanation2.setEnabled(false);
         explanation3.setEnabled(false);
         explanation4.setEnabled(false);
         explanation5.setEnabled(false);
         explanation6.setEnabled(false);
         explanation7.setEnabled(false);
         explanation8.setEnabled(false);
         explanation9.setEnabled(false);
         explanation10.setEnabled(false);
         watch w=new watch();
         w.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a1 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JRadioButton();
        c1 = new javax.swing.JRadioButton();
        d1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        a2 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        d2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        a3 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        c3 = new javax.swing.JRadioButton();
        d3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        a4 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        c4 = new javax.swing.JRadioButton();
        d4 = new javax.swing.JRadioButton();
        a5 = new javax.swing.JRadioButton();
        b5 = new javax.swing.JRadioButton();
        c5 = new javax.swing.JRadioButton();
        d5 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        check1 = new javax.swing.JButton();
        explanation1 = new javax.swing.JButton();
        check2 = new javax.swing.JButton();
        explanation2 = new javax.swing.JButton();
        check3 = new javax.swing.JButton();
        explanation3 = new javax.swing.JButton();
        check4 = new javax.swing.JButton();
        explanation4 = new javax.swing.JButton();
        check5 = new javax.swing.JButton();
        explanation5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        a6 = new javax.swing.JRadioButton();
        b6 = new javax.swing.JRadioButton();
        c6 = new javax.swing.JRadioButton();
        d6 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        a7 = new javax.swing.JRadioButton();
        b7 = new javax.swing.JRadioButton();
        c7 = new javax.swing.JRadioButton();
        d7 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        a8 = new javax.swing.JRadioButton();
        c8 = new javax.swing.JRadioButton();
        b8 = new javax.swing.JRadioButton();
        d8 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        a9 = new javax.swing.JRadioButton();
        b9 = new javax.swing.JRadioButton();
        c9 = new javax.swing.JRadioButton();
        d9 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        a10 = new javax.swing.JRadioButton();
        b10 = new javax.swing.JRadioButton();
        c10 = new javax.swing.JRadioButton();
        d10 = new javax.swing.JRadioButton();
        check6 = new javax.swing.JButton();
        explanation6 = new javax.swing.JButton();
        check7 = new javax.swing.JButton();
        explanation7 = new javax.swing.JButton();
        check8 = new javax.swing.JButton();
        explanation8 = new javax.swing.JButton();
        check9 = new javax.swing.JButton();
        explanation9 = new javax.swing.JButton();
        check10 = new javax.swing.JButton();
        explanation10 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Stage 1 - Normal   ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 375, 56);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Answer more than 5 questions correctly  to proceed your contest!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 73, 527, 32);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("1.Which is correct to say: a)\"The yolk of the egg is white\". b)\"The yolk of the egg are white?\"");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 111, 687, 35);

        buttonGroup1.add(a1);
        a1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a1.setText("a");
        getContentPane().add(a1);
        a1.setBounds(10, 148, 120, 31);

        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b1.setText("b");
        getContentPane().add(b1);
        b1.setBounds(198, 148, 70, 31);

        buttonGroup1.add(c1);
        c1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c1.setText("both");
        getContentPane().add(c1);
        c1.setBounds(10, 176, 80, 31);

        buttonGroup1.add(d1);
        d1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d1.setText("none of the above");
        getContentPane().add(d1);
        d1.setBounds(198, 176, 170, 31);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("2. Introducing a girl, Santhosh said, “Her mother is the only daughter of my mother-in-law”. ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 210, 687, 33);

        buttonGroup2.add(a2);
        a2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a2.setText("Daughter of Santhosh");
        getContentPane().add(a2);
        a2.setBounds(10, 280, 183, 31);

        buttonGroup2.add(b2);
        b2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b2.setText("Mother of Santhosh");
        getContentPane().add(b2);
        b2.setBounds(210, 280, 180, 31);

        buttonGroup2.add(c2);
        c2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c2.setText("Wife of Santhosh");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(10, 310, 180, 31);

        buttonGroup2.add(d2);
        d2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d2.setText("Sister of Santhosh");
        getContentPane().add(d2);
        d2.setBounds(210, 310, 160, 31);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("3.What has hands but doesn’t clap?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 340, 301, 39);

        buttonGroup3.add(a3);
        a3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a3.setText("Human");
        getContentPane().add(a3);
        a3.setBounds(20, 380, 100, 31);

        buttonGroup3.add(b3);
        b3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b3.setText("Baby");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(190, 380, 80, 31);

        buttonGroup3.add(c3);
        c3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c3.setText("Clock");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3);
        c3.setBounds(20, 410, 80, 31);

        buttonGroup3.add(d3);
        d3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d3.setText("Computer");
        getContentPane().add(d3);
        d3.setBounds(190, 410, 100, 31);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("4.I am an odd number. Take away a letter and I become even. What number am I?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 451, 663, 34);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("5.You look a little down in the dumps.Choose the meaning of the Phrase. ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 560, 550, 40);

        buttonGroup4.add(a4);
        a4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a4.setText("7");
        getContentPane().add(a4);
        a4.setBounds(10, 500, 60, 31);

        buttonGroup4.add(b4);
        b4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b4.setText("19");
        getContentPane().add(b4);
        b4.setBounds(180, 500, 70, 31);

        buttonGroup4.add(c4);
        c4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c4.setText("4");
        getContentPane().add(c4);
        c4.setBounds(10, 530, 50, 31);

        buttonGroup4.add(d4);
        d4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d4.setText("18");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });
        getContentPane().add(d4);
        d4.setBounds(180, 530, 50, 31);

        buttonGroup5.add(a5);
        a5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a5.setText("You are looking down");
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        getContentPane().add(a5);
        a5.setBounds(10, 600, 190, 31);

        buttonGroup5.add(b5);
        b5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b5.setText("You look sad");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(210, 600, 130, 30);

        buttonGroup5.add(c5);
        c5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c5.setText("You look great");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5);
        c5.setBounds(10, 639, 160, 31);

        buttonGroup5.add(d5);
        d5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d5.setText("You look a little angry");
        d5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d5ActionPerformed(evt);
            }
        });
        getContentPane().add(d5);
        d5.setBounds(210, 640, 200, 31);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("How is Santhosh related to the girl?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 240, 370, 30);

        check1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check1.setText("check");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        getContentPane().add(check1);
        check1.setBounds(410, 160, 90, 40);

        explanation1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation1.setText("explanation");
        explanation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation1ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation1);
        explanation1.setBounds(520, 160, 140, 40);

        check2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check2.setText("check");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });
        getContentPane().add(check2);
        check2.setBounds(410, 260, 90, 40);

        explanation2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation2.setText("Explanation");
        explanation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation2ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation2);
        explanation2.setBounds(520, 260, 140, 40);

        check3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check3.setText("check");
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });
        getContentPane().add(check3);
        check3.setBounds(409, 390, 100, 40);

        explanation3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation3.setText("Explanation");
        explanation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation3ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation3);
        explanation3.setBounds(530, 390, 140, 40);

        check4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check4.setText("check");
        check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check4ActionPerformed(evt);
            }
        });
        getContentPane().add(check4);
        check4.setBounds(410, 510, 90, 40);

        explanation4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation4.setText("Explanation");
        explanation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation4ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation4);
        explanation4.setBounds(530, 510, 140, 40);

        check5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check5.setText("check");
        check5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check5ActionPerformed(evt);
            }
        });
        getContentPane().add(check5);
        check5.setBounds(410, 600, 90, 40);

        explanation5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation5.setText("Explanation");
        explanation5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation5ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation5);
        explanation5.setBounds(530, 600, 150, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("6. Look at this series: 12, 11, 13, 12, 14, 13, … What number should come next?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(730, 80, 620, 40);

        buttonGroup6.add(a6);
        a6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        a6.setText("11");
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        getContentPane().add(a6);
        a6.setBounds(740, 130, 50, 25);

        buttonGroup6.add(b6);
        b6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        b6.setText("12");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(900, 130, 50, 25);

        buttonGroup6.add(c6);
        c6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        c6.setText("16");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        getContentPane().add(c6);
        c6.setBounds(740, 160, 50, 25);

        buttonGroup6.add(d6);
        d6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        d6.setText("15");
        getContentPane().add(d6);
        d6.setBounds(900, 160, 60, 25);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("7. At one's fingertips. Find the meaning of the idiom.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(720, 190, 490, 40);

        buttonGroup7.add(a7);
        a7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a7.setText("To take revenge");
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });
        getContentPane().add(a7);
        a7.setBounds(740, 240, 150, 31);

        buttonGroup7.add(b7);
        b7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b7.setText("Matter of Shame");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(940, 240, 170, 31);

        buttonGroup7.add(c7);
        c7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c7.setText("Complete Knowledge");
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });
        getContentPane().add(c7);
        c7.setBounds(740, 270, 190, 31);

        buttonGroup7.add(d7);
        d7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d7.setText("None of the above");
        getContentPane().add(d7);
        d7.setBounds(940, 270, 170, 31);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("8. I can only live where there is light but if a light shines on me, I die. What am I?");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(720, 300, 650, 40);

        buttonGroup8.add(a8);
        a8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a8.setText("Shadow");
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });
        getContentPane().add(a8);
        a8.setBounds(740, 340, 90, 31);

        buttonGroup8.add(c8);
        c8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c8.setText("water");
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });
        getContentPane().add(c8);
        c8.setBounds(740, 370, 80, 31);

        buttonGroup8.add(b8);
        b8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b8.setText("light");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(920, 340, 70, 31);

        buttonGroup8.add(d8);
        d8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d8.setText("Bulb");
        d8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d8ActionPerformed(evt);
            }
        });
        getContentPane().add(d8);
        d8.setBounds(920, 370, 80, 31);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("9.Rita studied for the tests______ late into the night.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(720, 400, 460, 40);

        buttonGroup9.add(a9);
        a9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a9.setText("since");
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });
        getContentPane().add(a9);
        a9.setBounds(740, 440, 70, 31);

        buttonGroup9.add(b9);
        b9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b9.setText("before");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(920, 440, 90, 31);

        buttonGroup9.add(c9);
        c9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c9.setText("until");
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });
        getContentPane().add(c9);
        c9.setBounds(740, 470, 70, 31);

        buttonGroup9.add(d9);
        d9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d9.setText("although");
        getContentPane().add(d9);
        d9.setBounds(920, 470, 100, 31);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("10.Find out from____ ,when she will be back.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(720, 510, 370, 40);

        buttonGroup12.add(a10);
        a10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a10.setText("she");
        getContentPane().add(a10);
        a10.setBounds(740, 550, 60, 31);

        buttonGroup12.add(b10);
        b10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b10.setText("her");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10);
        b10.setBounds(920, 550, 60, 20);

        buttonGroup12.add(c10);
        c10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c10.setText("hers");
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });
        getContentPane().add(c10);
        c10.setBounds(740, 580, 70, 20);

        buttonGroup12.add(d10);
        d10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d10.setText("herself");
        d10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d10ActionPerformed(evt);
            }
        });
        getContentPane().add(d10);
        d10.setBounds(920, 580, 90, 31);

        check6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check6.setText("check");
        check6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check6ActionPerformed(evt);
            }
        });
        getContentPane().add(check6);
        check6.setBounds(1100, 130, 90, 40);

        explanation6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation6.setText("explanation");
        explanation6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation6ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation6);
        explanation6.setBounds(1200, 130, 150, 40);

        check7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check7.setText("check");
        check7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check7ActionPerformed(evt);
            }
        });
        getContentPane().add(check7);
        check7.setBounds(1110, 250, 80, 40);

        explanation7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation7.setText("explanation");
        explanation7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation7ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation7);
        explanation7.setBounds(1200, 250, 140, 40);

        check8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check8.setText("check");
        check8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check8ActionPerformed(evt);
            }
        });
        getContentPane().add(check8);
        check8.setBounds(1090, 360, 100, 40);

        explanation8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation8.setText("explanation");
        explanation8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation8ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation8);
        explanation8.setBounds(1200, 360, 140, 40);

        check9.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check9.setText("check");
        check9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check9ActionPerformed(evt);
            }
        });
        getContentPane().add(check9);
        check9.setBounds(1090, 460, 100, 40);

        explanation9.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation9.setText("explanation");
        explanation9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation9ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation9);
        explanation9.setBounds(1200, 460, 150, 40);

        check10.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check10.setText("check");
        check10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check10ActionPerformed(evt);
            }
        });
        getContentPane().add(check10);
        check10.setBounds(1090, 550, 100, 40);

        explanation10.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation10.setText("explanation");
        explanation10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation10ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation10);
        explanation10.setBounds(1200, 550, 150, 40);

        jButton21.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton21.setText("CALCULATE MY TOTAL MARKS IN STAGE 1");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(620, 650, 430, 50);

        jButton22.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton22.setText("PROCEED THE CONTEST");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(1080, 650, 260, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainred.jpeg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(200, -10, 460, 390);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainred.jpeg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, -6, 200, 380);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainred.jpeg"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 360, 460, 380);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainred.jpeg"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(460, 370, 400, 370);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainred.jpeg"))); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(860, 370, 370, 370);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1190, 460, 210, 60);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1190, 360, 210, 60);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(1190, 410, 210, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(1190, 433, 210, 60);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel24.setText("jLabel24");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(1190, 510, 210, 30);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel25.setText("jLabel25");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(1190, 540, 258, 43);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel26.setText("jLabel26");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(1190, 574, 210, 50);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel27.setText("jLabel27");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(1190, 620, 210, 43);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel28.setText("jLabel28");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(1190, 660, 210, 43);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design2.jpeg"))); // NOI18N
        jLabel29.setText("jLabel29");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(1190, 700, 210, 43);

        timer.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        getContentPane().add(timer);
        timer.setBounds(1110, 20, 50, 40);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel15.setText("TIMER:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1010, 20, 100, 33);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/level1.jpeg"))); // NOI18N
        jLabel30.setText("jLabel30");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(660, -10, 740, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a5ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void d5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d5ActionPerformed

    private void explanation5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation5ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "EXPLANATION: you look sad is the correct answer. It is the meaning of the idiom.");
    }//GEN-LAST:event_explanation5ActionPerformed

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        // TODO add your handling code here:
          explanation1.setEnabled(true);
        check1.setEnabled(false);
        a1.setEnabled(false);
         b1.setEnabled(false);
          c1.setEnabled(false);
           d1.setEnabled(false);
         if( d1.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            d1.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a1.isSelected())
            {
                 a1.setForeground(new Color(247,202,24));
            }
            else if(b1.isSelected())
            {
             b1.setForeground(new Color(247,202,24));   
            }
             else if(c1.isSelected())
            {
             c1.setForeground(new Color(247,202,24));   
            }
        }
    }//GEN-LAST:event_check1ActionPerformed

    private void explanation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION: None of the above is the correct answer because Color of the egg yolk is yellow!!");
    }//GEN-LAST:event_explanation1ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a6ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c7ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a8ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c8ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a9ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    private void d10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d10ActionPerformed

    private void explanation9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation9ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "EXPLANATION: until is the correct answer.Rita studied for the test until late into the night.");
        
    }//GEN-LAST:event_explanation9ActionPerformed

    private void check8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check8ActionPerformed
        // TODO add your handling code here:
         explanation8.setEnabled(true);
        check8.setEnabled(false);
        a8.setEnabled(false);
         b8.setEnabled(false);
          c8.setEnabled(false);
           d8.setEnabled(false);
         if( a8.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            a8.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(b8.isSelected())
            {
                b8.setForeground(new Color(247,202,24));
            }
            else if(c8.isSelected())
            {
             c8.setForeground(new Color(247,202,24));   
            }
             else if(d8.isSelected())
            {
             d8.setForeground(new Color(247,202,24));   
            }
        
    }                  
    }//GEN-LAST:event_check8ActionPerformed

    private void check10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check10ActionPerformed
        // TODO add your handling code here:
         explanation10.setEnabled(true);
        check10.setEnabled(false);
        a10.setEnabled(false);
         b10.setEnabled(false);
          c10.setEnabled(false);
           d10.setEnabled(false);
         if( b10.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            b10.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a10.isSelected())
            {
                a10.setForeground(new Color(247,202,24));
            }
            else if(c10.isSelected())
            {
             c10.setForeground(new Color(247,202,24));   
            }
             else if(d10.isSelected())
            {
             d10.setForeground(new Color(247,202,24));   
            }
        
    }                  
    }//GEN-LAST:event_check10ActionPerformed

    private void explanation7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation7ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "EXPLANATION: Complete Knowledge is the correct answer.Meaning of this idiom is Complete Knowledge.");
    }//GEN-LAST:event_explanation7ActionPerformed

    private void explanation6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation6ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "EXPLANATION: 15 is the correct answer.\nThis is an alternation number of series.First,1 is subtracted and \nthen 2 is added.");
    }//GEN-LAST:event_explanation6ActionPerformed

    private void explanation8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation8ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "EXPLANATION: Shadow is the correct answer.Riddle!!");
    }//GEN-LAST:event_explanation8ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void d8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d8ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c10ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You total score in stage 1 is:"+mark);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        
          if(mark>=4)
        {
            
        new level2(var).setVisible(true);
        this.setVisible(false);
        }
        if(mark<4)
        {
          new  thank().setVisible(true);
          this.setVisible(false);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d4ActionPerformed

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
        // TODO add your handling code here:
          explanation2.setEnabled(true);
        check2.setEnabled(false);
        a2.setEnabled(false);
         b2.setEnabled(false);
          c2.setEnabled(false);
           d2.setEnabled(false);
         if( a2.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            a2.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(b2.isSelected())
            {
                b2.setForeground(new Color(247,202,24));
            }
            else if(c2.isSelected())
            {
             c2.setForeground(new Color(247,202,24));   
            }
             else if(d2.isSelected())
            {
             d2.setForeground(new Color(247,202,24));   
            }
        }
    }//GEN-LAST:event_check2ActionPerformed

    private void check9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check9ActionPerformed
        // TODO add your handling code here:
         explanation9.setEnabled(true);
        check9.setEnabled(false);
        a9.setEnabled(false);
         b9.setEnabled(false);
          c9.setEnabled(false);
           d9.setEnabled(false);
         if( c9.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            c9.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(b9.isSelected())
            {
                b9.setForeground(new Color(247,202,24));
            }
            else if(a9.isSelected())
            {
             a9.setForeground(new Color(247,202,24));   
            }
             else if(d9.isSelected())
            {
             d9.setForeground(new Color(247,202,24));   
            }
        
    }                  
    }//GEN-LAST:event_check9ActionPerformed

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check3ActionPerformed
        // TODO add your handling code here:
         explanation3.setEnabled(true);
        check3.setEnabled(false);
        a3.setEnabled(false);
         b3.setEnabled(false);
          c3.setEnabled(false);
           d3.setEnabled(false);
         if( c3.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            c3.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a3.isSelected())
            {
                a3.setForeground(new Color(247,202,24));
            }
            else if(b3.isSelected())
            {
             b3.setForeground(new Color(247,202,24));   
            }
             else if(d3.isSelected())
            {
             d3.setForeground(new Color(247,202,24));   
            }
        }
                      
        
    }//GEN-LAST:event_check3ActionPerformed

    private void check4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check4ActionPerformed
        // TODO add your handling code here:
         explanation4.setEnabled(true);
        check4.setEnabled(false);
        a4.setEnabled(false);
         b4.setEnabled(false);
          c4.setEnabled(false);
           d4.setEnabled(false);
         if( a4.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            a4.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(b4.isSelected())
            {
                b4.setForeground(new Color(247,202,24));
            }
            else if(c4.isSelected())
            {
             c4.setForeground(new Color(247,202,24));   
            }
             else if(d4.isSelected())
            {
             d4.setForeground(new Color(247,202,24));   
            }
        }
                     
    }//GEN-LAST:event_check4ActionPerformed

    private void check5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check5ActionPerformed
        // TODO add your handling code here:
         explanation5.setEnabled(true);
        check5.setEnabled(false);
        a5.setEnabled(false);
         b5.setEnabled(false);
          c5.setEnabled(false);
           d5.setEnabled(false);
         if( b5.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            b5.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a5.isSelected())
            {
                a5.setForeground(new Color(247,202,24));
            }
            else if(c5.isSelected())
            {
             c5.setForeground(new Color(247,202,24));   
            }
             else if(d5.isSelected())
            {
             d5.setForeground(new Color(247,202,24));   
            }
        }
                      
    }//GEN-LAST:event_check5ActionPerformed

    private void check6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check6ActionPerformed
        // TODO add your handling code here:
         explanation6.setEnabled(true);
        check6.setEnabled(false);
        a6.setEnabled(false);
         b6.setEnabled(false);
          c6.setEnabled(false);
           d6.setEnabled(false);
         if( d6.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            d6.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a6.isSelected())
            {
                a6.setForeground(new Color(247,202,24));
            }
            else if(b6.isSelected())
            {
             b6.setForeground(new Color(247,202,24));   
            }
             else if(c6.isSelected())
            {
             c6.setForeground(new Color(247,202,24));   
            }
        }
                     
    }//GEN-LAST:event_check6ActionPerformed

    private void check7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check7ActionPerformed
        // TODO add your handling code here:
         explanation7.setEnabled(true);
        check7.setEnabled(false);
        a7.setEnabled(false);
         b7.setEnabled(false);
          c7.setEnabled(false);
           d7.setEnabled(false);
         if( c7.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            c7.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a7.isSelected())
            {
                a7.setForeground(new Color(247,202,24));
            }
            else if(b7.isSelected())
            {
             b7.setForeground(new Color(247,202,24));   
            }
             else if(d7.isSelected())
            {
             d7.setForeground(new Color(247,202,24));   
            }
        }
                    
    }//GEN-LAST:event_check7ActionPerformed

    private void explanation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION: Daughter of Santhosh is the correct answer.Her mother is my wife.So she is my daughter.");
    }//GEN-LAST:event_explanation2ActionPerformed

    private void explanation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation3ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "EXPLANATION: Clock is the correct answer.It has hour hand,minutes hand but it can't clap.");
    }//GEN-LAST:event_explanation3ActionPerformed

    private void explanation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation4ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "EXPLANATION: 7 is the correct answer.\nOdd=Seven \nEven=even. By removing 'S'");
    }//GEN-LAST:event_explanation4ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_c9ActionPerformed

    private void explanation10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation10ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "EXPLANATION: her is the correct answer.Find out from her,when she will be back");
    }//GEN-LAST:event_explanation10ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level1().setVisible(true);
            }
        });
    }

    class watch extends Thread
{
    int ms=61;
    public void run(){
        for(;;){
            try {
                while(ms!=0){
                sleep(1000);
                ms--;
                timer.setText(Integer.toString(ms));
                }
                check1.setEnabled(false);
                check2.setEnabled(false);
                check3.setEnabled(false);
                check4.setEnabled(false);
                check5.setEnabled(false);
                check6.setEnabled(false);
                check7.setEnabled(false);
                check8.setEnabled(false);
                check9.setEnabled(false);
                check10.setEnabled(false);
                a1.setEnabled(false);
                 b1.setEnabled(false);
                  c1.setEnabled(false);
                   d1.setEnabled(false);
                    a2.setEnabled(false);
                    b2.setEnabled(false);
                  c2.setEnabled(false);
                   d2.setEnabled(false);
                   a3.setEnabled(false);
                    b3.setEnabled(false);
                  c3.setEnabled(false);
                   d3.setEnabled(false);
                   a4.setEnabled(false);
                    b4.setEnabled(false);
                  c4.setEnabled(false);
                   d4.setEnabled(false);
                   a5.setEnabled(false);
                    b5.setEnabled(false);
                  c5.setEnabled(false);
                   d5.setEnabled(false);
                   a6.setEnabled(false);
                    b6.setEnabled(false);
                  c6.setEnabled(false);
                   d6.setEnabled(false);
                   a7.setEnabled(false);
                    b7.setEnabled(false);
                  c7.setEnabled(false);
                   d7.setEnabled(false);
                    a8.setEnabled(false);
                    b8.setEnabled(false);
                  c8.setEnabled(false);
                   d8.setEnabled(false);
        a9.setEnabled(false);
                    b9.setEnabled(false);
                  c9.setEnabled(false);
                   d9.setEnabled(false);
                   a10.setEnabled(false);
                    b10.setEnabled(false);
                  c10.setEnabled(false);
                   d10.setEnabled(false);
            } catch (InterruptedException ex) {
                Logger.getLogger(level1.class.getName()).log(Level.SEVERE, null, ex);
            }  
                //Logger.getLogger(.class.getName()).log(Level.SEVERE, null, ex);
            
            
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a10;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton a6;
    private javax.swing.JRadioButton a7;
    private javax.swing.JRadioButton a8;
    private javax.swing.JRadioButton a9;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b10;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JRadioButton b5;
    private javax.swing.JRadioButton b6;
    private javax.swing.JRadioButton b7;
    private javax.swing.JRadioButton b8;
    private javax.swing.JRadioButton b9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c10;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    private javax.swing.JRadioButton c4;
    private javax.swing.JRadioButton c5;
    private javax.swing.JRadioButton c6;
    private javax.swing.JRadioButton c7;
    private javax.swing.JRadioButton c8;
    private javax.swing.JRadioButton c9;
    private javax.swing.JButton check1;
    private javax.swing.JButton check10;
    private javax.swing.JButton check2;
    private javax.swing.JButton check3;
    private javax.swing.JButton check4;
    private javax.swing.JButton check5;
    private javax.swing.JButton check6;
    private javax.swing.JButton check7;
    private javax.swing.JButton check8;
    private javax.swing.JButton check9;
    private javax.swing.JRadioButton d1;
    private javax.swing.JRadioButton d10;
    private javax.swing.JRadioButton d2;
    private javax.swing.JRadioButton d3;
    private javax.swing.JRadioButton d4;
    private javax.swing.JRadioButton d5;
    private javax.swing.JRadioButton d6;
    private javax.swing.JRadioButton d7;
    private javax.swing.JRadioButton d8;
    private javax.swing.JRadioButton d9;
    private javax.swing.JButton explanation1;
    private javax.swing.JButton explanation10;
    private javax.swing.JButton explanation2;
    private javax.swing.JButton explanation3;
    private javax.swing.JButton explanation4;
    private javax.swing.JButton explanation5;
    private javax.swing.JButton explanation6;
    private javax.swing.JButton explanation7;
    private javax.swing.JButton explanation8;
    private javax.swing.JButton explanation9;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables
}
