/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Paarkavi Saravanan
 */
public class level3 extends javax.swing.JFrame {
     public int mark=0;
     String var;
    /**
     * Creates new form level3
     */
    public level3() {
        initComponents();
   setExtendedState(JFrame.MAXIMIZED_BOTH);
       explanation1.setEnabled(false);
         explanation2.setEnabled(false);
          explanation3.setEnabled(false);
           explanation4.setEnabled(false);
            explanation5.setEnabled(false);
             explanation6.setEnabled(false);
              explanation7.setEnabled(false);
               explanation8.setEnabled(false);
               watch w=new watch();
               w.start();
        
    }
    public level3(String a) {
        initComponents();
        var=a;
   setExtendedState(JFrame.MAXIMIZED_BOTH);
        explanation1.setEnabled(false);
         explanation2.setEnabled(false);
          explanation3.setEnabled(false);
           explanation4.setEnabled(false);
            explanation5.setEnabled(false);
             explanation6.setEnabled(false);
              explanation7.setEnabled(false);
               explanation8.setEnabled(false);
               watch w=new watch();
               w.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a1 = new javax.swing.JRadioButton();
        c1 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JRadioButton();
        d1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        a2 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        d2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        a3 = new javax.swing.JRadioButton();
        c3 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        d3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        check1 = new javax.swing.JButton();
        explanation1 = new javax.swing.JButton();
        check2 = new javax.swing.JButton();
        explanation2 = new javax.swing.JButton();
        check3 = new javax.swing.JButton();
        explanation3 = new javax.swing.JButton();
        check4 = new javax.swing.JButton();
        explanation4 = new javax.swing.JButton();
        check5 = new javax.swing.JButton();
        explanation5 = new javax.swing.JButton();
        check6 = new javax.swing.JButton();
        explanation6 = new javax.swing.JButton();
        check7 = new javax.swing.JButton();
        explanation7 = new javax.swing.JButton();
        check8 = new javax.swing.JButton();
        explanation8 = new javax.swing.JButton();
        d8 = new javax.swing.JRadioButton();
        b8 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        b4 = new javax.swing.JRadioButton();
        d4 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        c4 = new javax.swing.JRadioButton();
        b5 = new javax.swing.JRadioButton();
        a5 = new javax.swing.JRadioButton();
        d5 = new javax.swing.JRadioButton();
        c5 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        a6 = new javax.swing.JRadioButton();
        b6 = new javax.swing.JRadioButton();
        c6 = new javax.swing.JRadioButton();
        d6 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        b7 = new javax.swing.JRadioButton();
        d7 = new javax.swing.JRadioButton();
        a7 = new javax.swing.JRadioButton();
        c7 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a8 = new javax.swing.JRadioButton();
        c8 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Stage 3 - Hell of a mess");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 0, 510, 56);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Answer more than 5 questions correctly to get the certificate !!!  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 48, 520, 38);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("1. Which is the valid keyword in java ?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(203, 104, 310, 49);

        buttonGroup1.add(a1);
        a1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a1.setText("interface");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(220, 155, 110, 31);

        buttonGroup1.add(c1);
        c1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c1.setText("string");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(220, 190, 110, 31);

        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b1.setText("Float");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(375, 155, 80, 31);

        buttonGroup1.add(d1);
        d1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d1.setText("unsigned");
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1);
        d1.setBounds(375, 190, 100, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("2. What is the numerical range of a char?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(205, 210, 350, 39);

        buttonGroup2.add(a2);
        a2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a2.setText("-128 to 127");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        getContentPane().add(a2);
        a2.setBounds(220, 260, 110, 31);

        buttonGroup2.add(c2);
        c2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c2.setText("0 to 300");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(220, 290, 110, 31);

        buttonGroup2.add(b2);
        b2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b2.setText("0 to 32767");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(370, 260, 130, 31);

        buttonGroup2.add(d2);
        d2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d2.setText("0 to 65535");
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        getContentPane().add(d2);
        d2.setBounds(370, 290, 130, 31);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("3. What header file supports the functions -malloc() and calloc() ? ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(203, 330, 470, 33);

        buttonGroup3.add(a3);
        a3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a3.setText("stdlib.h");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        getContentPane().add(a3);
        a3.setBounds(220, 370, 120, 31);

        buttonGroup3.add(c3);
        c3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c3.setText("memory.h");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3);
        c3.setBounds(220, 400, 130, 31);

        buttonGroup3.add(b3);
        b3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b3.setText("math.h");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(390, 370, 80, 31);

        buttonGroup3.add(d3);
        d3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d3.setText("stdio.h");
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });
        getContentPane().add(d3);
        d3.setBounds(390, 400, 80, 31);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jButton1.setText("CALCULATE MY TOTAL SCORE IN STAGE 3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 630, 360, 52);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton2.setText("FINISH MY QUIZ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1090, 630, 210, 51);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setLayout(null);

        check1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check1.setText("check");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        jPanel1.add(check1);
        check1.setBounds(560, 140, 120, 30);

        explanation1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation1.setText("explanation");
        explanation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation1ActionPerformed(evt);
            }
        });
        jPanel1.add(explanation1);
        explanation1.setBounds(560, 180, 150, 30);

        check2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check2.setText("check");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });
        jPanel1.add(check2);
        check2.setBounds(560, 250, 110, 30);

        explanation2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation2.setText("explanation");
        explanation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation2ActionPerformed(evt);
            }
        });
        jPanel1.add(explanation2);
        explanation2.setBounds(560, 290, 150, 30);

        check3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check3.setText("check");
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });
        jPanel1.add(check3);
        check3.setBounds(560, 370, 100, 30);

        explanation3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation3.setText("explanation");
        explanation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation3ActionPerformed(evt);
            }
        });
        jPanel1.add(explanation3);
        explanation3.setBounds(560, 410, 140, 30);

        check4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check4.setText("check");
        check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check4ActionPerformed(evt);
            }
        });
        jPanel1.add(check4);
        check4.setBounds(560, 480, 81, 33);

        explanation4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation4.setText("explanation");
        explanation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation4ActionPerformed(evt);
            }
        });
        jPanel1.add(explanation4);
        explanation4.setBounds(560, 520, 150, 33);

        check5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check5.setText("check");
        check5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check5ActionPerformed(evt);
            }
        });
        jPanel1.add(check5);
        check5.setBounds(310, 650, 140, 30);

        explanation5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation5.setText("explanation");
        explanation5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation5ActionPerformed(evt);
            }
        });
        jPanel1.add(explanation5);
        explanation5.setBounds(470, 650, 140, 30);

        check6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check6.setText("check");
        check6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check6ActionPerformed(evt);
            }
        });
        jPanel1.add(check6);
        check6.setBounds(1210, 180, 100, 30);

        explanation6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation6.setText("explanation");
        explanation6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation6ActionPerformed(evt);
            }
        });
        jPanel1.add(explanation6);
        explanation6.setBounds(1210, 220, 160, 30);

        check7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check7.setText("check");
        check7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check7ActionPerformed(evt);
            }
        });
        jPanel1.add(check7);
        check7.setBounds(1230, 350, 90, 30);

        explanation7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation7.setText("explanation");
        explanation7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation7ActionPerformed(evt);
            }
        });
        jPanel1.add(explanation7);
        explanation7.setBounds(1230, 390, 150, 30);

        check8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check8.setText("check");
        check8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check8ActionPerformed(evt);
            }
        });
        jPanel1.add(check8);
        check8.setBounds(1240, 490, 100, 30);

        explanation8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation8.setText("explanation");
        explanation8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation8ActionPerformed(evt);
            }
        });
        jPanel1.add(explanation8);
        explanation8.setBounds(1240, 530, 150, 30);

        buttonGroup9.add(d8);
        d8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d8.setText("25");
        d8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d8ActionPerformed(evt);
            }
        });
        jPanel1.add(d8);
        d8.setBounds(1130, 500, 88, 31);

        buttonGroup9.add(b8);
        b8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b8.setText("264");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);
        b8.setBounds(1130, 470, 53, 31);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainblue.jpeg"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(1310, 0, 130, 380);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainblue.jpeg"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(1260, 370, 170, 360);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainblue.jpeg"))); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(330, 600, 680, 480);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainblue.jpeg"))); // NOI18N
        jLabel26.setText("jLabel26");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(160, 630, 180, 120);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel27.setText("jLabel27");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(50, 360, 120, 50);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel31.setText("jLabel31");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(50, 390, 130, 50);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel32.setText("jLabel32");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(50, 460, 130, 35);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel34.setText("jLabel34");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(50, 490, 130, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("5. Which one is a valid declaration of a boolean?");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 540, 434, 40);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel35.setText("jLabel35");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(50, 520, 130, 35);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel36.setText("jLabel36");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(50, 550, 130, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("4.How many types of polymorphisms are supported by C++ ?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 430, 510, 42);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel39.setText("jLabel39");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(50, 580, 130, 35);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel42.setText("jLabel42");
        jPanel1.add(jLabel42);
        jLabel42.setBounds(50, 630, 130, 40);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel43.setText("jLabel43");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(50, 600, 130, 40);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel44.setText("jLabel44");
        jPanel1.add(jLabel44);
        jLabel44.setBounds(50, 660, 130, 35);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel45.setText("jLabel45");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(50, 670, 110, 70);

        buttonGroup4.add(b4);
        b4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b4.setText("2");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(440, 490, 35, 31);

        buttonGroup4.add(d4);
        d4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d4.setText("4");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });
        jPanel1.add(d4);
        d4.setBounds(440, 520, 35, 31);

        buttonGroup4.add(a4);
        a4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a4.setText("1");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        jPanel1.add(a4);
        a4.setBounds(270, 480, 60, 31);

        buttonGroup4.add(c4);
        c4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c4.setText("3");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        jPanel1.add(c4);
        c4.setBounds(270, 510, 35, 31);

        buttonGroup7.add(b5);
        b5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b5.setText("boolean b2='false';");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(440, 580, 200, 31);

        buttonGroup7.add(a5);
        a5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a5.setText("boolean b1=0;");
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        jPanel1.add(a5);
        a5.setBounds(270, 580, 150, 31);

        buttonGroup7.add(d5);
        d5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d5.setText("boolean b4=no;");
        d5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d5ActionPerformed(evt);
            }
        });
        jPanel1.add(d5);
        d5.setBounds(440, 610, 190, 31);

        buttonGroup7.add(c5);
        c5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c5.setText("boolean b3=false;");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        jPanel1.add(c5);
        c5.setBounds(270, 610, 160, 31);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("6.What should be the output?");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(820, 140, 296, 38);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("int main() {");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(820, 180, 106, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("int a = 10/3;");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(820, 200, 98, 23);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("printf(\"%d\",a); ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(820, 220, 98, 28);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("return 0; } ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(820, 240, 120, 28);

        buttonGroup6.add(a6);
        a6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a6.setText("3.33");
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        jPanel1.add(a6);
        a6.setBounds(970, 180, 70, 31);

        buttonGroup6.add(b6);
        b6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b6.setText("3.0");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(1070, 180, 60, 31);

        buttonGroup6.add(c6);
        c6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c6.setText("3");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        jPanel1.add(c6);
        c6.setBounds(970, 210, 60, 31);

        buttonGroup6.add(d6);
        d6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d6.setText("0");
        d6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d6ActionPerformed(evt);
            }
        });
        jPanel1.add(d6);
        d6.setBounds(1070, 210, 50, 31);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("7.How many main() function we can have in our project?");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(820, 290, 454, 42);

        buttonGroup8.add(b7);
        b7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b7.setText("2");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(1030, 340, 50, 31);

        buttonGroup8.add(d7);
        d7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d7.setText("Depends on Compiler");
        d7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d7ActionPerformed(evt);
            }
        });
        jPanel1.add(d7);
        d7.setBounds(1030, 370, 190, 31);

        buttonGroup8.add(a7);
        a7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a7.setText("1");
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });
        jPanel1.add(a7);
        a7.setBounds(850, 340, 50, 31);

        buttonGroup8.add(c7);
        c7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c7.setText("No Limit");
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });
        jPanel1.add(c7);
        c7.setBounds(850, 370, 94, 31);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("8.Guess the output.");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(810, 420, 244, 32);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("public class CppBuzz{");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(820, 460, 169, 23);

        buttonGroup9.add(a8);
        a8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a8.setText("138");
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });
        jPanel1.add(a8);
        a8.setBounds(1050, 470, 52, 31);

        buttonGroup9.add(c8);
        c8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c8.setText("41");
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });
        jPanel1.add(c8);
        c8.setBounds(1050, 500, 52, 31);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("public static void main(String args[]){");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(820, 490, 244, 25);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("int a=5+5*2+2*2+(2*3);");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(820, 520, 169, 29);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("System.out.println(a); } }");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(820, 550, 169, 23);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainblue.jpeg"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(170, 374, 530, 280);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainblue.jpeg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(690, 280, 310, 380);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainblue.jpeg"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(780, 0, 550, 380);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainblue.jpeg"))); // NOI18N
        jLabel28.setText("jLabel28");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(860, 327, 410, 460);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel33.setText("jLabel33");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(50, 410, 120, 70);

        timer.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jPanel1.add(timer);
        timer.setBounds(170, 130, 70, 40);

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel19.setText("Timer:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(80, 130, 80, 40);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/level3.jpeg"))); // NOI18N
        jLabel46.setText("jLabel46");
        jPanel1.add(jLabel46);
        jLabel46.setBounds(43, -6, 890, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-50, 0, 1430, 770);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(590, 590, 100, 100);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(450, 630, 340, 50);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(870, 630, 180, 50);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 140, 73, 23);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel30.setText("jLabel30");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(0, 430, 173, 35);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel29.setText("jLabel29");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(0, 400, 130, 40);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel37.setText("jLabel37");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(0, 600, 120, 35);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel40.setText("jLabel40");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(0, 630, 100, 40);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design3.jpeg"))); // NOI18N
        jLabel41.setText("jLabel41");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(0, 620, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_a1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_c1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_b1ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_d1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_c2ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_a2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_b2ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_d2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_a3ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_b3ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_c3ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_d3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_a4ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_b4ActionPerformed

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_d4ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        
    }//GEN-LAST:event_c4ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_a6ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
      
    }//GEN-LAST:event_b6ActionPerformed

    private void d6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d6ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_d6ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_c6ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_a5ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_b5ActionPerformed

    private void d5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d5ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_d5ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_c5ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_a7ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_b7ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_c7ActionPerformed

    private void d7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_d7ActionPerformed

    private void d8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d8ActionPerformed
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_d8ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
        
    }//GEN-LAST:event_a8ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
       
    }//GEN-LAST:event_b8ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
      
    }//GEN-LAST:event_c8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"Your total score in Stage 3 is: "+mark);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(mark>4)
        {
        new certifi(var).setVisible(true);
        this.setVisible(false);
        }
        if(mark<=4)
        {
            new thank().setVisible(true);
            this.setVisible(false);
        }
        
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        // TODO add your handling code here:
        explanation1.setEnabled(true);
        check1.setEnabled(false);
        a1.setEnabled(false);
         b1.setEnabled(false);
          c1.setEnabled(false);
           d1.setEnabled(false);
         if( a1.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            a1.setForeground(new Color(0,255,0));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(b1.isSelected())
            {
                 b1.setForeground(new Color(242,38,19));
            }
            else if(d1.isSelected())
            {
             d1.setForeground(new Color(242,38,19));   
            }
             else if(b1.isSelected())
            {
             b1.setForeground(new Color(242,38,19));   
            }
        }
    }//GEN-LAST:event_check1ActionPerformed

    private void explanation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION:!interface is a valid keyword.\n  'String' is a class type in java,'string' is not a keyword. \n 'Float' is a class type. The keyword for the java primitive is float. \n  'unsigned' is a keyword in C/C++ but not in java ");
    }//GEN-LAST:event_explanation1ActionPerformed

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
        // TODO add your handling code here:
         explanation2.setEnabled(true);
        check2.setEnabled(false);
        a2.setEnabled(false);
         b2.setEnabled(false);
          c2.setEnabled(false);
           d2.setEnabled(false);
         if( d2.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            d2.setForeground(new Color(0,255,0));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a2.isSelected())
            {
                 a2.setForeground(new Color(242,38,19));
            }
            else if(b2.isSelected())
            {
             b2.setForeground(new Color(242,38,19));   
            }
             else if(c2.isSelected())
            {
             c2.setForeground(new Color(242,38,19));   
            }
        }
    }//GEN-LAST:event_check2ActionPerformed

    private void explanation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION:  A char is really a 16 bit integer behind the scenes,\n so it supports 2^16(0 to 65535) values  ");
    }//GEN-LAST:event_explanation2ActionPerformed

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check3ActionPerformed
        // TODO add your handling code here:
        explanation3.setEnabled(true);
        check3.setEnabled(false);
        a3.setEnabled(false);
         b3.setEnabled(false);
          c3.setEnabled(false);
           d3.setEnabled(false);
         if( a3.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            a3.setForeground(new Color(0,255,0));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(b3.isSelected())
            {
                 b3.setForeground(new Color(242,38,19));
            }
            else if(c3.isSelected())
            {
             c3.setForeground(new Color(242,38,19));   
            }
             else if(d3.isSelected())
            {
             d3.setForeground(new Color(242,38,19));   
            }
        }
    }//GEN-LAST:event_check3ActionPerformed

    private void explanation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION:stdlib.h is a correct answer!!void *malloc(size_t size): allocates the requested memory and returns a pointer to it.\n void *calloc(size_t size): Allocates the requested memory and returns a pointer to it ");
    }//GEN-LAST:event_explanation3ActionPerformed

    private void check4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check4ActionPerformed
        // TODO add your handling code here:
        explanation4.setEnabled(true);
        check4.setEnabled(false);
        a4.setEnabled(false);
         b4.setEnabled(false);
          c4.setEnabled(false);
           d4.setEnabled(false);
         if( c4.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            c4.setForeground(new Color(0,255,0));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a4.isSelected())
            {
                 a4.setForeground(new Color(242,38,19));
            }
            else if(b4.isSelected())
            {
             b4.setForeground(new Color(242,38,19));   
            }
             else if(d3.isSelected())
            {
             d4.setForeground(new Color(242,38,19));   
            }
        }
    }//GEN-LAST:event_check4ActionPerformed

    private void explanation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION: C++ supports 3 types of polymorphism .\nThey are 1) ad-hoc polymorphism \n2) parametric polymorphism \n3) subtype polymorphism");
    }//GEN-LAST:event_explanation4ActionPerformed

    private void check5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check5ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        explanation5.setEnabled(true);
        check5.setEnabled(false);
        a5.setEnabled(false);
         b5.setEnabled(false);
          c5.setEnabled(false);
           d5.setEnabled(false);
         if( c5.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            c5.setForeground(new Color(0,255,0));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a5.isSelected())
            {
                 a5.setForeground(new Color(242,38,19));
            }
            else if(b5.isSelected())
            {
             b5.setForeground(new Color(242,38,19));   
            }
             else if(d5.isSelected())
            {
             d5.setForeground(new Color(242,38,19));   
            }
        }
    }//GEN-LAST:event_check5ActionPerformed

    private void explanation5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION: boolean b3=false is a correct answer.\nA boolean can only be assigned the literal true or false ");
    }//GEN-LAST:event_explanation5ActionPerformed

    private void check6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check6ActionPerformed
        // TODO add your handling code here:
         explanation6.setEnabled(true);
        check6.setEnabled(false);
        a6.setEnabled(false);
         b6.setEnabled(false);
          c6.setEnabled(false);
           d6.setEnabled(false);
         if( c6.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            c6.setForeground(new Color(0,255,0));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a6.isSelected())
            {
                 a6.setForeground(new Color(242,38,19));
            }
            else if(b6.isSelected())
            {
             b6.setForeground(new Color(242,38,19));   
            }
             else if(d6.isSelected())
            {
             d6.setForeground(new Color(242,38,19));   
            }
        }
    }//GEN-LAST:event_check6ActionPerformed

    private void explanation6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION: 3 is a correct answer!! \ninteger division ( int/ int ) is int only hence instead of printing 3.33 it will print 3 only. \nFloat part is discarded in such cases.");
        
    }//GEN-LAST:event_explanation6ActionPerformed

    private void check7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check7ActionPerformed
        // TODO add your handling code here:
         explanation7.setEnabled(true);
        check7.setEnabled(false);
        a7.setEnabled(false);
         b7.setEnabled(false);
          c7.setEnabled(false);
           d7.setEnabled(false);
         if( a7.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            a7.setForeground(new Color(0,255,0));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(b7.isSelected())
            {
                 b7.setForeground(new Color(242,38,19));
            }
            else if(c7.isSelected())
            {
             c7.setForeground(new Color(242,38,19));   
            }
             else if(c7.isSelected())
            {
             c7.setForeground(new Color(242,38,19));   
            }
        }
    }//GEN-LAST:event_check7ActionPerformed

    private void explanation7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION: \n1 is a correct answer. \nWe can't have more than one main function in a project.");
    }//GEN-LAST:event_explanation7ActionPerformed

    private void check8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check8ActionPerformed
        // TODO add your handling code here:
        explanation8.setEnabled(true);
        check8.setEnabled(false);
        a8.setEnabled(false);
         b8.setEnabled(false);
          c8.setEnabled(false);
           d8.setEnabled(false);
         if( d8.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            d8.setForeground(new Color(0,255,0));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a8.isSelected())
            {
                 a8.setForeground(new Color(242,38,19));
            }
            else if(c8.isSelected())
            {
             c8.setForeground(new Color(242,38,19));   
            }
             else if(b8.isSelected())
            {
             b8.setForeground(new Color(242,38,19));   
            }
        }
    }//GEN-LAST:event_check8ActionPerformed

    private void explanation8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation8ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION: \n25 is correct. \n It is evaluated as 5+10+4+6");
    }//GEN-LAST:event_explanation8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level3().setVisible(true);
            }
        });
    }
     class watch extends Thread
{
    int ms=51;
    public void run(){
        for(;;){
            try {
                while(ms!=0){
                sleep(1000);
                ms--;
                timer.setText(Integer.toString(ms));
                }
                check1.setEnabled(false);
                check2.setEnabled(false);
                check3.setEnabled(false);
                check4.setEnabled(false);
                check5.setEnabled(false);
                a1.setEnabled(false);
                 b1.setEnabled(false);
                  c1.setEnabled(false);
                   d1.setEnabled(false);
                    a2.setEnabled(false);
                 b2.setEnabled(false);
                  c2.setEnabled(false);
                   d2.setEnabled(false);
                a3.setEnabled(false);
                 b3.setEnabled(false);
                  c3.setEnabled(false);
                   d3.setEnabled(false);
                 a4.setEnabled(false);
                    b4.setEnabled(false);
                  c4.setEnabled(false);
                   d4.setEnabled(false);
                   a6.setEnabled(false);
                    b6.setEnabled(false);
                  c6.setEnabled(false);
                   d6.setEnabled(false);
                   a7.setEnabled(false);
                    b7.setEnabled(false);
                  c7.setEnabled(false);
                   d7.setEnabled(false);
                    a8.setEnabled(false);
                    b8.setEnabled(false);
                  c8.setEnabled(false);
                   d8.setEnabled(false);
                     a5.setEnabled(false);
                    b5.setEnabled(false);
                  c5.setEnabled(false);
                   d5.setEnabled(false);
                  check6.setEnabled(false);
                  check7.setEnabled(false);
                  check8.setEnabled(false);
                   
                  
            } catch (InterruptedException ex) {
                Logger.getLogger(level1.class.getName()).log(Level.SEVERE, null, ex);
            }  
                //Logger.getLogger(.class.getName()).log(Level.SEVERE, null, ex);
            
            
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton a6;
    private javax.swing.JRadioButton a7;
    private javax.swing.JRadioButton a8;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JRadioButton b5;
    private javax.swing.JRadioButton b6;
    private javax.swing.JRadioButton b7;
    private javax.swing.JRadioButton b8;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    private javax.swing.JRadioButton c4;
    private javax.swing.JRadioButton c5;
    private javax.swing.JRadioButton c6;
    private javax.swing.JRadioButton c7;
    private javax.swing.JRadioButton c8;
    private javax.swing.JButton check1;
    private javax.swing.JButton check2;
    private javax.swing.JButton check3;
    private javax.swing.JButton check4;
    private javax.swing.JButton check5;
    private javax.swing.JButton check6;
    private javax.swing.JButton check7;
    private javax.swing.JButton check8;
    private javax.swing.JRadioButton d1;
    private javax.swing.JRadioButton d2;
    private javax.swing.JRadioButton d3;
    private javax.swing.JRadioButton d4;
    private javax.swing.JRadioButton d5;
    private javax.swing.JRadioButton d6;
    private javax.swing.JRadioButton d7;
    private javax.swing.JRadioButton d8;
    private javax.swing.JButton explanation1;
    private javax.swing.JButton explanation2;
    private javax.swing.JButton explanation3;
    private javax.swing.JButton explanation4;
    private javax.swing.JButton explanation5;
    private javax.swing.JButton explanation6;
    private javax.swing.JButton explanation7;
    private javax.swing.JButton explanation8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables
}
