/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Paarkavi Saravanan
 */
public class level2 extends javax.swing.JFrame {
     public int mark=0;
     String var;
    /**
     * Creates new form level2
     */
    public level2() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        explanation1.setEnabled(false);
         explanation2.setEnabled(false);
          explanation3.setEnabled(false);
           explanation4.setEnabled(false);
            explanation5.setEnabled(false);
         setExtendedState(JFrame.MAXIMIZED_BOTH);
         watch w=new watch();
         w.start();
        
    }
     public level2(String a) {
        initComponents();
        var=a;
        explanation1.setEnabled(false);
         explanation2.setEnabled(false);
          explanation3.setEnabled(false);
           explanation4.setEnabled(false);
            explanation5.setEnabled(false);
         setExtendedState(JFrame.MAXIMIZED_BOTH);
         watch w=new watch();
         w.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a1 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JRadioButton();
        c1 = new javax.swing.JRadioButton();
        d1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        a2 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        d2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        a3 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        c3 = new javax.swing.JRadioButton();
        d3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a4 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        c4 = new javax.swing.JRadioButton();
        d4 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        a5 = new javax.swing.JRadioButton();
        c5 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        b5 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        d5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        check1 = new javax.swing.JButton();
        check2 = new javax.swing.JButton();
        check3 = new javax.swing.JButton();
        check4 = new javax.swing.JButton();
        check5 = new javax.swing.JButton();
        explanation1 = new javax.swing.JButton();
        explanation2 = new javax.swing.JButton();
        explanation3 = new javax.swing.JButton();
        explanation4 = new javax.swing.JButton();
        explanation5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Stage 2 - i - Nightmare  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 540, 56);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Answer more than 5 questions correctly to proceed the contest!!! ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 70, 514, 35);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("1.A Number of stars grouped together ?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(148, 110, 360, 32);

        buttonGroup1.add(a1);
        a1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a1.setText("Solar system");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(150, 160, 120, 31);

        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b1.setText("Galaxy");
        getContentPane().add(b1);
        b1.setBounds(290, 160, 90, 31);

        buttonGroup1.add(c1);
        c1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c1.setText("Constellation");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(150, 190, 130, 31);

        buttonGroup1.add(d1);
        d1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d1.setText("Asteroids");
        getContentPane().add(d1);
        d1.setBounds(290, 190, 93, 31);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("2.If in a certain language,MADRAS is coded as NBESBT.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 230, 480, 31);

        buttonGroup2.add(a2);
        a2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a2.setText("CPNCBX");
        getContentPane().add(a2);
        a2.setBounds(170, 300, 110, 31);

        buttonGroup2.add(b2);
        b2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b2.setText("CPOCBZ");
        getContentPane().add(b2);
        b2.setBounds(290, 300, 97, 31);

        buttonGroup2.add(c2);
        c2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c2.setText("CPNCBZ");
        getContentPane().add(c2);
        c2.setBounds(170, 330, 97, 31);

        buttonGroup2.add(d2);
        d2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d2.setText("CQOCBZ");
        getContentPane().add(d2);
        d2.setBounds(290, 330, 99, 31);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("3.First actor to get OSCAR AWARD.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 380, 544, 38);

        buttonGroup3.add(a3);
        a3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a3.setText("Charlie Chaplin");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        getContentPane().add(a3);
        a3.setBounds(160, 440, 120, 31);

        buttonGroup3.add(b3);
        b3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b3.setText("Emil Jannings");
        getContentPane().add(b3);
        b3.setBounds(290, 440, 130, 31);

        buttonGroup3.add(c3);
        c3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c3.setText("Montgomery");
        getContentPane().add(c3);
        c3.setBounds(160, 470, 130, 31);

        buttonGroup3.add(d3);
        d3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d3.setText("Fairbanks");
        getContentPane().add(d3);
        d3.setBounds(290, 470, 95, 31);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("4.If the value of this is 5.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(790, 110, 202, 31);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/WhatsApp Image 2020-11-05 at 4.34.06 AM.jpeg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(820, 160, 100, 73);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText(" =5");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(920, 180, 60, 31);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Find the value for this?");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1000, 110, 170, 31);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/WhatsApp Image 2020-11-05 at 4.34.36 AM.jpeg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1000, 140, 113, 103);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setText("   =?");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1110, 180, 66, 25);

        buttonGroup4.add(a4);
        a4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a4.setText("10");
        getContentPane().add(a4);
        a4.setBounds(1220, 160, 60, 31);

        buttonGroup4.add(b4);
        b4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b4.setText("11");
        getContentPane().add(b4);
        b4.setBounds(1290, 160, 43, 31);

        buttonGroup4.add(c4);
        c4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c4.setText("9");
        getContentPane().add(c4);
        c4.setBounds(1220, 190, 35, 31);

        buttonGroup4.add(d4);
        d4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d4.setText("14");
        getContentPane().add(d4);
        d4.setBounds(1290, 190, 60, 31);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("5.Find the Next Image.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(790, 310, 200, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/ques8.jpeg"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(790, 360, 200, 230);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/option1.jpeg"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(1040, 380, 80, 70);

        buttonGroup5.add(a5);
        a5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a5.setText("image1");
        getContentPane().add(a5);
        a5.setBounds(1020, 360, 99, 31);

        buttonGroup5.add(c5);
        c5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c5.setText("image2");
        getContentPane().add(c5);
        c5.setBounds(1020, 460, 90, 31);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/option2.jpeg"))); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(1040, 490, 80, 70);

        buttonGroup5.add(b5);
        b5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b5.setText("image3");
        getContentPane().add(b5);
        b5.setBounds(1210, 350, 90, 31);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/optio3.jpeg"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1210, 370, 80, 70);

        buttonGroup5.add(d5);
        d5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d5.setText("none of the above");
        d5.setToolTipText("");
        getContentPane().add(d5);
        d5.setBounds(1200, 490, 180, 31);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton1.setText("CALCULATE MY TOTAL MARKS IN STAGE 2-I");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 630, 450, 40);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(420, 630, 450, 40);

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton2.setText("PROCEED THE CONTEST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(930, 630, 270, 40);

        check1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check1.setText("check");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        getContentPane().add(check1);
        check1.setBounds(410, 170, 90, 30);

        check2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check2.setText("check");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });
        getContentPane().add(check2);
        check2.setBounds(420, 330, 90, 30);

        check3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check3.setText("check");
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });
        getContentPane().add(check3);
        check3.setBounds(430, 440, 90, 33);

        check4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check4.setText("check");
        check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check4ActionPerformed(evt);
            }
        });
        getContentPane().add(check4);
        check4.setBounds(1190, 240, 100, 33);

        check5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check5.setText("check");
        check5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check5ActionPerformed(evt);
            }
        });
        getContentPane().add(check5);
        check5.setBounds(1210, 530, 100, 40);

        explanation1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation1.setText("explanation");
        explanation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation1ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation1);
        explanation1.setBounds(510, 170, 140, 30);

        explanation2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation2.setText("explanation");
        explanation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation2ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation2);
        explanation2.setBounds(530, 330, 140, 33);

        explanation3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation3.setText("explanation");
        explanation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation3ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation3);
        explanation3.setBounds(540, 440, 140, 30);

        explanation4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation4.setText("explanation");
        explanation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation4ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation4);
        explanation4.setBounds(1190, 280, 140, 30);

        explanation5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation5.setText("explanation");
        explanation5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation5ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation5);
        explanation5.setBounds(1210, 580, 150, 40);
        getContentPane().add(jPanel5);
        jPanel5.setBounds(680, 0, 0, 580);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Then how BOMBAY is coded?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 260, 270, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/level2.jpeg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 740, 380);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1264, -10, 160, 390);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(880, 370, 690, 340);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(340, 350, 570, 360);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 370, 130, 80);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel24.setText("jLabel24");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 440, 130, 72);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel25.setText("jLabel25");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(0, 510, 130, 70);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel26.setText("jLabel26");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(0, 580, 130, 72);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel27.setText("jLabel27");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 650, 130, 60);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel28.setText("jLabel28");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(120, 370, 220, 340);

        timer.setFont(new java.awt.Font("Trebuchet MS", 3, 48)); // NOI18N
        getContentPane().add(timer);
        timer.setBounds(1110, 30, 100, 60);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel6.setText("Timer:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1000, 30, 110, 50);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel29.setText("jLabel29");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(730, -10, 560, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        // TODO add your handling code here:
        explanation1.setEnabled(true);
        check1.setEnabled(false);
        a1.setEnabled(false);
         b1.setEnabled(false);
          c1.setEnabled(false);
           d1.setEnabled(false);
        
        if( c1.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            c1.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a1.isSelected())
            {
                 a1.setForeground(new Color(246,71,71));
            }
            else if(b1.isSelected())
            {
             b1.setForeground(new Color(246,71,71));   
            }
             else if(d1.isSelected())
            {
             d1.setForeground(new Color(246,71,71));   
            }
            
            
        }
    }//GEN-LAST:event_check1ActionPerformed

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
        // TODO add your handling code here:
        explanation2.setEnabled(true);
        check2.setEnabled(false);
        a2.setEnabled(false);
         b2.setEnabled(false);
          c2.setEnabled(false);
           d2.setEnabled(false);
        if( c2.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is: "+mark);
            c2.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a2.isSelected())
            {
                 a2.setForeground(new Color(246,71,71));
            }
            else if(b2.isSelected())
            {
             b2.setForeground(new Color(246,71,71));   
            }
             else if(d2.isSelected())
            {
             d2.setForeground(new Color(246,71,71));   
            }
        }
        
    }//GEN-LAST:event_check2ActionPerformed

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check3ActionPerformed
        // TODO add your handling code here:
        explanation3.setEnabled(true);
        check3.setEnabled(false);
        a3.setEnabled(false);
         b3.setEnabled(false);
          c3.setEnabled(false);
           d3.setEnabled(false);
         if( b3.isSelected())
        {
            mark++;
           // JOptionPane.showMessageDialog(null, "your score is:"+mark);
            b3.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a3.isSelected())
            {
                 a3.setForeground(new Color(246,71,71));
            }
            else if(c3.isSelected())
            {
             c3.setForeground(new Color(246,71,71));   
            }
             else if(d3.isSelected())
            {
             d3.setForeground(new Color(246,71,71)); 
            }
        }
    }//GEN-LAST:event_check3ActionPerformed

    private void check4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check4ActionPerformed
        // TODO add your handling code here:
        explanation4.setEnabled(true);
       check4.setEnabled(false);
        a4.setEnabled(false);
         b4.setEnabled(false);
          c4.setEnabled(false);
           d4.setEnabled(false);
         if( d4.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is: "+mark);
            d4.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(b4.isSelected())
            {
                 b4.setForeground(new Color(246,71,71));
            }
            else if(c4.isSelected())
            {
             c4.setForeground(new Color(246,71,71));   
            }
             else if(a4.isSelected())
            {
             a4.setForeground(new Color(246,71,71));   
            }
        }
    }//GEN-LAST:event_check4ActionPerformed

    private void check5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check5ActionPerformed
        // TODO add your handling code here:
        explanation5.setEnabled(true);
        check5.setEnabled(false);
        a5.setEnabled(false);
         b5.setEnabled(false);
          c5.setEnabled(false);
           d5.setEnabled(false);
         if( b5.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            b5.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a5.isSelected())
            {
                 a5.setForeground(new Color(246,71,71));
            }
            else if(c5.isSelected())
            {
             c5.setForeground(new Color(246,71,71));   
            }
             else if(d5.isSelected())
            {
             d5.setForeground(new Color(246,71,71));   
            }
        }
    }//GEN-LAST:event_check5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Your total score is: "+mark);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void explanation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation1ActionPerformed
        // TODO add your handling code here:
     JOptionPane.showMessageDialog(null, "EXPLANATION:A constellation is a group of stars that appears to form a pattern or picture ");
    }//GEN-LAST:event_explanation1ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void explanation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"EXPLANATION: Each letter in the word is move one step forward to obtain the coresponding letter of the code!!");
    }//GEN-LAST:event_explanation2ActionPerformed

    private void explanation5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"EXPLANATION: Logical Thinking");
    }//GEN-LAST:event_explanation5ActionPerformed

    private void explanation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"EXPLANTION: He got this award for the best actor for his leading role in 'SILENT' film");
    }//GEN-LAST:event_explanation3ActionPerformed

    private void explanation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"EXPLANATION:Total no. of square = 14 ");
    }//GEN-LAST:event_explanation4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(mark>=2)
        {
            new level2_ii(var).setVisible(true);
            this.setVisible(false);
        }
        if(mark<2)
        {
            new  thank().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level2().setVisible(true);
            }
        });
    }
    class watch extends Thread
{
    int ms=26;
    public void run(){
        for(;;){
            try {
                while(ms!=0){
                sleep(1000);
                ms--;
                timer.setText(Integer.toString(ms));
                }
                check1.setEnabled(false);
                check2.setEnabled(false);
                check3.setEnabled(false);
                check4.setEnabled(false);
                check5.setEnabled(false);
               
                a1.setEnabled(false);
                 b1.setEnabled(false);
                  c1.setEnabled(false);
                   d1.setEnabled(false);
                    a2.setEnabled(false);
                    b2.setEnabled(false);
                  c2.setEnabled(false);
                   d2.setEnabled(false);
                   a3.setEnabled(false);
                    b3.setEnabled(false);
                  c3.setEnabled(false);
                   d3.setEnabled(false);
                   a4.setEnabled(false);
                    b4.setEnabled(false);
                  c4.setEnabled(false);
                   d4.setEnabled(false);
                   a5.setEnabled(false);
                    b5.setEnabled(false);
                  c5.setEnabled(false);
                   d5.setEnabled(false);
                  
            } catch (InterruptedException ex) {
                Logger.getLogger(level1.class.getName()).log(Level.SEVERE, null, ex);
            }  
                //Logger.getLogger(.class.getName()).log(Level.SEVERE, null, ex);
            
            
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JRadioButton b5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    private javax.swing.JRadioButton c4;
    private javax.swing.JRadioButton c5;
    private javax.swing.JButton check1;
    private javax.swing.JButton check2;
    private javax.swing.JButton check3;
    private javax.swing.JButton check4;
    private javax.swing.JButton check5;
    private javax.swing.JRadioButton d1;
    private javax.swing.JRadioButton d2;
    private javax.swing.JRadioButton d3;
    private javax.swing.JRadioButton d4;
    private javax.swing.JRadioButton d5;
    private javax.swing.JButton explanation1;
    private javax.swing.JButton explanation2;
    private javax.swing.JButton explanation3;
    private javax.swing.JButton explanation4;
    private javax.swing.JButton explanation5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables
}
