/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Paarkavi Saravanan
 */
public class level2_ii extends javax.swing.JFrame {
public int mark=0;
String var;
    /**
     * Creates new form level2_ii
     */
    public level2_ii() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        explanation1.setEnabled(false);
        explanation2.setEnabled(false);
         explanation3.setEnabled(false);
         explanation4.setEnabled(false);
        explanation5.setEnabled(false);
        watch w=new watch();
        w.start();
    }
     public level2_ii(String a) {
        initComponents();
        var=a;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        explanation1.setEnabled(false);
        explanation2.setEnabled(false);
         explanation3.setEnabled(false);
         explanation4.setEnabled(false);
        explanation5.setEnabled(false);
        watch w=new watch();
        w.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a1 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JRadioButton();
        c1 = new javax.swing.JRadioButton();
        d1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        a2 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        d2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        a3 = new javax.swing.JRadioButton();
        c3 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        d3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        a4 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        c4 = new javax.swing.JRadioButton();
        d4 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        a5 = new javax.swing.JRadioButton();
        b5 = new javax.swing.JRadioButton();
        c5 = new javax.swing.JRadioButton();
        d5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        check1 = new javax.swing.JButton();
        explanation1 = new javax.swing.JButton();
        check2 = new javax.swing.JButton();
        explanation2 = new javax.swing.JButton();
        check3 = new javax.swing.JButton();
        explanation3 = new javax.swing.JButton();
        check4 = new javax.swing.JButton();
        explanation4 = new javax.swing.JButton();
        check5 = new javax.swing.JButton();
        explanation5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Stage 2 - ii - specter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(212, 30, 450, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Answer more than 2 question correctly to proceed the contest!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 100, 480, 31);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("1. If 12 students in a class failed in both art and science ,10failed in art,but 22 failed in ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 632, 27);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Science.How many students were in total?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 190, 390, 31);

        buttonGroup1.add(a1);
        a1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a1.setText("10");
        getContentPane().add(a1);
        a1.setBounds(170, 240, 50, 31);

        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b1.setText("20");
        getContentPane().add(b1);
        b1.setBounds(280, 240, 60, 31);

        buttonGroup1.add(c1);
        c1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c1.setText("30");
        getContentPane().add(c1);
        c1.setBounds(170, 280, 50, 31);

        buttonGroup1.add(d1);
        d1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d1.setText("40");
        getContentPane().add(d1);
        d1.setBounds(280, 280, 43, 31);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("2. Longest Dam in India is");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 320, 361, 37);

        buttonGroup2.add(a2);
        a2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a2.setText("Hirakud Dam");
        getContentPane().add(a2);
        a2.setBounds(80, 370, 130, 31);

        buttonGroup2.add(b2);
        b2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b2.setText("Bhakra Dam");
        getContentPane().add(b2);
        b2.setBounds(250, 370, 120, 31);

        buttonGroup2.add(c2);
        c2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c2.setText("Chilka Lake");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(80, 410, 130, 31);

        d2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(d2);
        d2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d2.setText("Kallanai Dam");
        getContentPane().add(d2);
        d2.setBounds(250, 410, 130, 31);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("3.How many times can you subtract the number 5 from 25?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 470, 470, 37);

        buttonGroup3.add(a3);
        a3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a3.setText("3 times");
        getContentPane().add(a3);
        a3.setBounds(100, 510, 90, 31);

        buttonGroup3.add(c3);
        c3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c3.setText("5 times");
        getContentPane().add(c3);
        c3.setBounds(100, 550, 90, 31);

        buttonGroup3.add(b3);
        b3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b3.setText("1 time");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(250, 510, 90, 31);

        buttonGroup3.add(d3);
        d3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d3.setText("8 times");
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });
        getContentPane().add(d3);
        d3.setBounds(250, 550, 90, 31);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("4.If it's value is 5.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(660, 50, 183, 36);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/WhatsApp Image 2020-11-05 at 6.32.16 AM.jpeg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(970, 90, 420, 270);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Then , find it's value.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(980, 50, 275, 36);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/WhatsApp Image 2020-11-05 at 6.31.36 AM.jpeg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(660, 90, 290, 270);

        buttonGroup4.add(a4);
        a4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a4.setText("19");
        getContentPane().add(a4);
        a4.setBounds(720, 390, 60, 31);

        buttonGroup4.add(b4);
        b4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b4.setText("10");
        getContentPane().add(b4);
        b4.setBounds(850, 390, 70, 31);

        buttonGroup4.add(c4);
        c4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c4.setText("27");
        getContentPane().add(c4);
        c4.setBounds(720, 420, 99, 23);

        buttonGroup4.add(d4);
        d4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d4.setText("18");
        getContentPane().add(d4);
        d4.setBounds(850, 420, 60, 31);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("5. What can you catch but cannot throw?");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(700, 470, 700, 40);

        a5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a5.setText("A tennis ball");
        getContentPane().add(a5);
        a5.setBounds(710, 510, 130, 31);

        b5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b5.setText("toys");
        getContentPane().add(b5);
        b5.setBounds(860, 510, 70, 31);

        c5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c5.setText("glass");
        getContentPane().add(c5);
        c5.setBounds(710, 550, 80, 31);

        d5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d5.setText("cold");
        d5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d5ActionPerformed(evt);
            }
        });
        getContentPane().add(d5);
        d5.setBounds(860, 550, 80, 31);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton1.setText("CALCULATE MY TOTAL MARK IN STAGE 2-II ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 600, 480, 50);

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("PROCEED THE CONTEST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1080, 600, 250, 50);

        check1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check1.setText("check");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        getContentPane().add(check1);
        check1.setBounds(420, 240, 100, 30);

        explanation1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation1.setText("explanation");
        explanation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation1ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation1);
        explanation1.setBounds(420, 280, 140, 30);

        check2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check2.setText("check");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });
        getContentPane().add(check2);
        check2.setBounds(420, 360, 110, 30);

        explanation2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation2.setText("explanation");
        explanation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation2ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation2);
        explanation2.setBounds(420, 400, 140, 30);

        check3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check3.setText("check");
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });
        getContentPane().add(check3);
        check3.setBounds(430, 510, 90, 30);

        explanation3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation3.setText("explanation");
        explanation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation3ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation3);
        explanation3.setBounds(430, 550, 150, 30);

        check4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check4.setText("check");
        check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check4ActionPerformed(evt);
            }
        });
        getContentPane().add(check4);
        check4.setBounds(1050, 390, 110, 33);

        explanation4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation4.setText("explanation");
        explanation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation4ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation4);
        explanation4.setBounds(1190, 390, 150, 30);

        check5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        check5.setText("check");
        check5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check5ActionPerformed(evt);
            }
        });
        getContentPane().add(check5);
        check5.setBounds(1060, 540, 110, 30);

        explanation5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        explanation5.setText("explanation");
        explanation5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanation5ActionPerformed(evt);
            }
        });
        getContentPane().add(explanation5);
        explanation5.setBounds(1200, 540, 150, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(680, 0, 540, 360);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1220, 0, 220, 360);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(120, 360, 540, 330);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(660, 360, 540, 330);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 354, 120, 70);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 420, 120, 80);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 490, 130, 80);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 560, 130, 80);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/design.jpeg"))); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 630, 130, 60);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plainpurple.jpeg"))); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(1190, 360, 250, 330);

        timer.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        getContentPane().add(timer);
        timer.setBounds(90, 50, 70, 50);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel13.setText("Timer:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 60, 80, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/level2.jpeg"))); // NOI18N
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(0, -10, 680, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        // TODO add your handling code here:
         explanation1.setEnabled(true);
        check1.setEnabled(false);
        a1.setEnabled(false);
         b1.setEnabled(false);
          c1.setEnabled(false);
           d1.setEnabled(false);
         if( b1.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            b1.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a1.isSelected())
            {
                 a1.setForeground(new Color(246,71,71));
            }
            else if(c1.isSelected())
            {
             c1.setForeground(new Color(246,71,71));   
            }
             else if(d1.isSelected())
            {
             d1.setForeground(new Color(246,71,71));   
            }
        }
    }//GEN-LAST:event_check1ActionPerformed

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
        // TODO add your handling code here:
         explanation2.setEnabled(true);
        check2.setEnabled(false);
        a2.setEnabled(false);
         b2.setEnabled(false);
          c2.setEnabled(false);
           d2.setEnabled(false);
         if( a2.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            a2.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(b2.isSelected())
            {
                 b2.setForeground(new Color(246,71,71));
            }
            else if(c2.isSelected())
            {
             c2.setForeground(new Color(246,71,71));   
            }
             else if(d2.isSelected())
            {
             d2.setForeground(new Color(246,71,71));   
            }
        }
    }//GEN-LAST:event_check2ActionPerformed

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check3ActionPerformed
        // TODO add your handling code here:
         explanation3.setEnabled(true);
        check3.setEnabled(false);
        a3.setEnabled(false);
         b3.setEnabled(false);
          c3.setEnabled(false);
           d3.setEnabled(false);
         if( b3.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            b3.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a3.isSelected())
            {
                 a3.setForeground(new Color(246,71,71));
            }
            else if(c3.isSelected())
            {
             c3.setForeground(new Color(246,71,71));   
            }
             else if(d3.isSelected())
            {
             d3.setForeground(new Color(246,71,71));   
            }
        }
     
    }//GEN-LAST:event_check3ActionPerformed

    private void check4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check4ActionPerformed
        // TODO add your handling code here:
         explanation4.setEnabled(true);
        check4.setEnabled(false);
        a4.setEnabled(false);
         b4.setEnabled(false);
          c4.setEnabled(false);
           d4.setEnabled(false);
         if( b4.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            b4.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a4.isSelected())
            {
                 a4.setForeground(new Color(246,71,71));
            }
            else if(c4.isSelected())
            {
             c4.setForeground(new Color(246,71,71));   
            }
             else if(d4.isSelected())
            {
             d4.setForeground(new Color(246,71,71));   
            }
        }
     
    }//GEN-LAST:event_check4ActionPerformed

    private void check5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check5ActionPerformed
        // TODO add your handling code here:
         explanation5.setEnabled(true);
        check5.setEnabled(false);
        a5.setEnabled(false);
         b5.setEnabled(false);
          c5.setEnabled(false);
           d5.setEnabled(false);
         if( d5.isSelected())
        {
            mark++;
            //JOptionPane.showMessageDialog(null, "your score is:"+mark);
            d5.setForeground(new Color(0,230,64));
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "wrong answer");
            if(a5.isSelected())
            {
                 a5.setForeground(new Color(256,71,71));
            }
            else if(c5.isSelected())
            {
             c5.setForeground(new Color(256,71,71));   
            }
             else if(d5.isSelected())
            {
             d5.setForeground(new Color(256,71,71));   
            }
        }
     
    }//GEN-LAST:event_check5ActionPerformed

    private void explanation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION: 10+22 = 32\n32-12=20");
    }//GEN-LAST:event_explanation1ActionPerformed

    private void explanation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "EXPLANATION:  Largest Dam: Hirakud Dam , length= 4.8 km");
    }//GEN-LAST:event_explanation2ActionPerformed

    private void explanation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"EXPLANATION: Because after you subtract, it is not 25 anymore!!");
    }//GEN-LAST:event_explanation3ActionPerformed

    private void explanation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation4ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"EXPLANATion: based on counting, no, of triangle=10");
    }//GEN-LAST:event_explanation4ActionPerformed

    private void explanation5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanation5ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"EXPLANATION: Riddle");
    }//GEN-LAST:event_explanation5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(mark>=2)
        {
        new level3(var).setVisible(true);
        this.setVisible(false);
        }
        if(mark<2)
        {
          new  thank().setVisible(true);
          this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Your total score is: "+mark);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void d5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d5ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level2_ii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level2_ii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level2_ii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level2_ii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level2_ii().setVisible(true);
            }
        });
    }
      class watch extends Thread
{
    int ms=31;
    public void run(){
        for(;;){
            try {
                while(ms!=0){
                sleep(1000);
                ms--;
                timer.setText(Integer.toString(ms));
                }
                check1.setEnabled(false);
                check2.setEnabled(false);
                check3.setEnabled(false);
                check4.setEnabled(false);
                check5.setEnabled(false);
               
                a1.setEnabled(false);
                 b1.setEnabled(false);
                  c1.setEnabled(false);
                   d1.setEnabled(false);
                    a2.setEnabled(false);
                    b2.setEnabled(false);
                  c2.setEnabled(false);
                   d2.setEnabled(false);
                   a3.setEnabled(false);
                    b3.setEnabled(false);
                  c3.setEnabled(false);
                   d3.setEnabled(false);
                   a4.setEnabled(false);
                    b4.setEnabled(false);
                  c4.setEnabled(false);
                   d4.setEnabled(false);
                   a5.setEnabled(false);
                    b5.setEnabled(false);
                  c5.setEnabled(false);
                   d5.setEnabled(false);
                  
            } catch (InterruptedException ex) {
                Logger.getLogger(level1.class.getName()).log(Level.SEVERE, null, ex);
            }  
                //Logger.getLogger(.class.getName()).log(Level.SEVERE, null, ex);
            
            
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JRadioButton b5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    private javax.swing.JRadioButton c4;
    private javax.swing.JRadioButton c5;
    private javax.swing.JButton check1;
    private javax.swing.JButton check2;
    private javax.swing.JButton check3;
    private javax.swing.JButton check4;
    private javax.swing.JButton check5;
    private javax.swing.JRadioButton d1;
    private javax.swing.JRadioButton d2;
    private javax.swing.JRadioButton d3;
    private javax.swing.JRadioButton d4;
    private javax.swing.JRadioButton d5;
    private javax.swing.JButton explanation1;
    private javax.swing.JButton explanation2;
    private javax.swing.JButton explanation3;
    private javax.swing.JButton explanation4;
    private javax.swing.JButton explanation5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables
}
