/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JFrame;

/**
 *
 * @author Paarkavi Saravanan
 */
public class rules extends javax.swing.JFrame {

    String var;

    /**
     * Creates new form rules
     */
    public rules() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public rules(String a) {
        
        initComponents();
        var=a;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/rule pic.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 337, 377);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel2.setText("SPECIFICATION:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(710, 10, 330, 50);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel4.setText("A GENTLE REMAINDER: This quiz is time limited quiz. So finish as soon as possible.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 60, 820, 40);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setText("If the selected option is correct , then the font color will change to ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 420, 490, 40);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("1. This quiz consist of three levels.They are listed below,");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(520, 100, 430, 40);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel6.setText("LEVEL          NO.OF QUESTIONS        CONDITION TO PROCEED THE QUIZ          TIME LIMIT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 140, 930, 40);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setText("1                                 10                                                atleast 5 correct answers                       50 seconds");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(540, 180, 870, 40);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setText("2  - A                          5                                                 atleast 3 correct answers                       25 seconds");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(540, 220, 830, 40);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setText("2  - B                          5                                                 atleast 2 correct answers                       25 seconds");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(540, 260, 830, 40);

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setText("3                                 8                                                 atleast 4 correct answers                       50 seconds");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(540, 300, 830, 40);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setText("or");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1100, 450, 30, 40);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 102));
        jLabel12.setText("GREEN.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1020, 420, 80, 40);

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setText("2. After selecting an option ,press the CHECK button to see your answer is correct or not. ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(500, 390, 760, 40);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel15.setText("DISABLED.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1020, 580, 100, 30);

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel16.setText("8.If you have completed the quiz successfully,CERTIFICATE will be provided!!!");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(500, 660, 880, 40);

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 0));
        jLabel17.setText("YELLOW");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1010, 460, 100, 30);

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel19.setText("If the selected option is wrong,then the font color will  change to   ");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(530, 450, 487, 40);

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel20.setText("3. For each correct answer 1 MARK will be awarded and for wrong answer NO MARK will be awarded.");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(500, 480, 820, 40);

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel21.setText("4. For each question a button called EXPLANATION is available which will be enabled only after ");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(500, 510, 820, 40);

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel22.setText("checking the answer and  gives a reason for the correct answer.");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(520, 540, 820, 40);

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("RED .");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(1130, 460, 100, 30);

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabel18.setText("PROCEED TO THE NEXT LEVEL.");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(510, 370, 510, 25);

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(510, 370, 510, 25);

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabel25.setText("AT EACH LEVEL,IF THE ABOVE  CONDITION IS NOT SATISFIED  THEN YOU WILL NOT BE ABLE TO  ");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(510, 340, 770, 25);

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel26.setText("5. Once the time is up,the CHECK button and the OPTIONS become ");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(500, 570, 520, 40);

        jLabel27.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel27.setText("6.To know your marks at each level, press the CALCULATE MY MARK button");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(500, 600, 760, 40);

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel28.setText("7.After finishing each level,press the PROCEED THE CONTEST button to proceed .At the end,press FINSH button .");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(500, 630, 880, 40);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/allthebest.gif"))); // NOI18N
        jLabel29.setText("jLabel29");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(70, 390, 220, 190);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jButton1.setText("TAKE MY QUIZ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 640, 210, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //String s=firstname.getText();
        new level1(var).setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
